import living_definition

ALL = []

ANY          = living_definition.Any(); ALL.append(ANY)
BAT          = living_definition.Bat(); ALL.append(BAT)
BLAZE        = living_definition.Blaze(); ALL.append(BLAZE)
CAVE_SPIDER  = living_definition.CaveSpider(); ALL.append(CAVE_SPIDER)
CHICKEN      = living_definition.Chicken(); ALL.append(CHICKEN)
COW          = living_definition.Cow(); ALL.append(COW)
CREEPER      = living_definition.Creeper(); ALL.append(CREEPER)
ENDER_DRAGON = living_definition.EnderDragon(); ALL.append(ENDER_DRAGON)
ENDERMAN     = living_definition.Enderman(); ALL.append(ENDERMAN)
ENDERMITE    = living_definition.Endermite(); ALL.append(ENDERMITE)
GHAST        = living_definition.Ghast(); ALL.append(GHAST)
GIANT        = living_definition.Giant(); ALL.append(GIANT)
GUARDIAN     = living_definition.Guardian(); ALL.append(GUARDIAN)
HORSE        = living_definition.Horse(); ALL.append(HORSE)
HUMAN        = living_definition.Human(); ALL.append(HUMAN)
IRON_GOLEM   = living_definition.IronGolem(); ALL.append(IRON_GOLEM)
MAGMA_CUBE   = living_definition.MagmaCube(); ALL.append(MAGMA_CUBE)
MUSHROOM_COW = living_definition.MushroomCow(); ALL.append(MUSHROOM_COW)
OCELOT       = living_definition.Ocelot(); ALL.append(OCELOT)
PIG          = living_definition.Pig(); ALL.append(PIG)
PIG_ZOMBIE   = living_definition.PigZombie(); ALL.append(PIG_ZOMBIE)
RABBIT       = living_definition.Rabbit(); ALL.append(RABBIT)
SHEEP        = living_definition.Sheep(); ALL.append(SHEEP)
SILVERFISH   = living_definition.Silverfish(); ALL.append(SILVERFISH)
SKELETON     = living_definition.Skeleton(); ALL.append(SKELETON)
SLIME        = living_definition.Slime(); ALL.append(SLIME)
SNOWMAN      = living_definition.Snowman(); ALL.append(SNOWMAN)
SPIDER       = living_definition.Spider(); ALL.append(SPIDER)
SQUID        = living_definition.Squid(); ALL.append(SQUID)
VILLAGER     = living_definition.Villager(); ALL.append(VILLAGER)
WITCH        = living_definition.Witch(); ALL.append(WITCH)
WITHER       = living_definition.Wither(); ALL.append(WITHER)
WOLF         = living_definition.Wolf(); ALL.append(WOLF)
ZOMBIE       = living_definition.Zombie(); ALL.append(ZOMBIE)
